/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.malekd5.uniusage;

import io.github.malekd5.uniusage.cli.CommandMap;

public class Main {

    public static void main(String... argv) {
        new CommandMap().execute(argv);
    }

}
