/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("org.jcommander:jcommander:2.0")

    implementation("com.clearspring.analytics:stream:2.9.6")

    // This dependency is used by the application.
    implementation(libs.guava)
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "io.github.malekd5.uniusage.Main"
        )
    }
}
// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "io.github.malekd5.uniusage.Main"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.shadowJar {
    archiveFileName.set("app-all.jar") // optional: name of the fat jar
    manifest {
        attributes(
             "Main-Class" to "io.github.malekd5.uniusage.Main"
        )
    }
}