/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.malekd5.uniticker;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {

    }
}
