name: Test, Build, and Release UniUsage CLI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build the JAR
        run: ./gradlew build

      - name: Get version for release
        id: version
        run: |
          MAJOR=1
          MINOR=0
          DATE=$(date +'%d%m%Y')
          echo "RELEASE_VERSION=${MAJOR}.${MINOR}-${DATE}" >> $GITHUB_OUTPUT

      - name: Generate changelog from commits
        id: changelog
        run: |
          LAST_TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "## Changes" > changelog.md
          if [ -z "$LAST_TAG" ]; then
            git log --pretty=format:"- %s" >> changelog.md
          else
            git log --pretty=format:"- %s" "$LAST_TAG"..HEAD >> changelog.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release v${{ steps.version.outputs.RELEASE_VERSION }}"
          tag_name: "v${{ steps.version.outputs.RELEASE_VERSION }}"
          body_path: changelog.md
          files: app/build/libs/UniUsage.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
